volumes:
  pg_data:
  front_static:

services:
  gateway:
    build: ./gateway
    volumes:
      - front_static:/var/www/front/dist
    ports:
      - 5060:80
  front:
    build: ./front
    command: cp -r /app/dist/. /static/
    volumes:
      - front_static:/static/
  fast_api:
    build: ./fastapi_app
    env_file:
      - ./.env
    ports:
      - '9000:9000'
  audiosocket:
    build: ./media_sockets
    env_file:
      - ./.env
    ports:
      - '7575:7575'
