volumes:
  front_static:

services:
  gateway:
    image: bkevg/ai_caller-gateway:latest
    volumes:
      - front_static:/var/www/frontend/
    ports:
      - '5060:80'
  front:
    image: bkevg/ai_caller-frontend:latest
    command: cp -r /app/dist/. /static/
    volumes:
      - front_static:/static/
  backend:
    image: bkevg/ai_caller-backend:latest
    env_file:
      - ./.env
    ports:
      - '5000:9000'
  audiosocket:
    image: bkevg/ai_caller-audio_socket:latest
    env_file:
      - ./.env
    ports:
      - '7575:7575'
