
services:
  gateway:
    build: ./gateway
    ports:
      - 5060:80
  fast_api:
    build: ./fastapi_app
    env_file:
      - ./.env
    ports:
      - '9000:9000'
  audiosocket:
    build: ./media_sockets
    env_file:
      - ./.env
    ports:
      - '7575:7575'
