volumes:
  postgres_data:

x-common: &service-common
  restart: always
  env_file:
    - .env

services:
  gateway:
    <<: *service-common
    image: bkevg/ai_caller-gateway:latest
    ports:
      - '5060:80'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      backend:
        condition: service_healthy
  backend:
    <<: *service-common
    image: bkevg/ai_caller-backend:latest
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
  audiosocket:
    <<: *service-common
    image: bkevg/ai_caller-audio_socket:latest
    ports:
      - '7575:7575'
  postgres:
    <<: *service-common
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready" ,"-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

