services:
  asterisk:
    image: asterisk:latest
    container_name: asterisk
    volumes:
      - ./asterisk_service/config:/etc/asterisk
      - ./asterisk_service/scripts:/var/lib/asterisk/agi-bin
    ports:
      - "5060:5060/udp"
      - "5038:5038"