
services:
  gateway:
    image: bkevg/ai_caller-gateway:latest
    ports:
      - '5060:80'
  backend:
    image: bkevg/ai_caller-backend:latest
    env_file:
      - ./.env
  audiosocket:
    image: bkevg/ai_caller-audio_socket:latest
    env_file:
      - ./.env
    ports:
      - '7575:7575'
